server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.108:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.0.108:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data_type: json
            rule-type: flow
            #[
            #{
            #  "resource": "/rateLimit/byUrl",
            #  "limitApp": "default",
            #  "grade": 1,
            #  "count": 1,
            #  "strategy": 0,
            #  "controlBehavior": 0,
            #  "clusterMode": false
            #}
            #]
management:
  endpoints:
    web:
      exposure:
        include: "*"
#https://github.com/alibaba/Sentinel/wiki/ Sentinel使用介绍